# Project information
site_name: 'SiLago Documentation'
site_description: 'Documentation of SiLago project'
site_author: 'SiLago Team'
site_url: 'https://herenvarno.github.io/SiLagoDoc/'

# Repository
repo_name: 'SiLagoGit/SiLago'
repo_url : 'https://gitr.sys.kth.se/SiLagoGit/SiLago'

pages:
  - Home: index.md
  - Docs:
    - Getstart:
      - Docs/Start/Overview.md
      - Docs/Start/Source-code-organization.md
      - Docs/Start/Quick-guide-for-code-documentation.md
      - Docs/Start/Quick-guide-for-naming-system.md
    - Fabric:
      - Docs/Fabric/Overview.md
      - DRRA:
        - Docs/Fabric/DRRA/RACCU.md
      - RISC V:
        - Docs/Fabric/RISCV/Overview.md
    - Tool Chain:
      - Docs/ToolChain/Overview.md
      - Vesyla:
        - Docs/ToolChain/Vesyla/Overview.md
        - Docs/ToolChain/Vesyla/Tutorial.md
        - Docs/ToolChain/Vesyla/ProgrammingGuide.md
        - Docs/ToolChain/Vesyla/Instruction-Set.md
        - Docs/ToolChain/Vesyla/Cidfg.md
        - Docs/ToolChain/Vesyla/Scheduling.md
        - Docs/ToolChain/Vesyla/DiMArch.md
      - Sylva:
        - Docs/ToolChain/Sylva/Overview.md
    - Library:
      - Docs/Library/Overview.md
      - BLAS:
        - Docs/Library/BLAS/Overview.md
      - NN:
        - Docs/Library/NN/Overview.md
      - Interleaver:
        - Docs/Library/Interleaver/Overview.md
      - FFT:
        - Docs/Library/FFT/Overview.md
    - Appliction:
      - Docs/Application/Overview.md
      - SiLagoDSP:
        - Docs/Application/SiLagoDSP/Fast-Fourier-Projection.md
  - About:
      - About/About.md
      - About/License.md

theme:
  name: 'material'
  font:
    text: 'Lato'
    code: 'Roboto Mono'
  feature:
    tabs: true
  palette:
    primary: 'light green'
    accent: 'orange'

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      linenums: true
  - toc
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - mdx_inline_graphviz

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

