version: 2
jobs:
  build:
    branches:
      only: master
    environment:
      CIRCLE_BRANCH: master
      TZ: '/usr/share/zoneinfo/Etc/UTC'
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    docker:
      - image: circleci/python:3.6-jessie-browsers
    steps:
      - checkout
      - run: sudo apt-get install graphviz
      - run: sudo pip install -q mkdocs mkdocs-material pygments graphviz markdown_inline_graphviz_extension
      - run:
          name: Special version of inline_graphviz
          command: sudo pip install git+https://github.com/sprin/markdown-inline-graphviz.git@9664863b3002d88243c9ee5e14c195e037e54618#egg=markdown-inline-graphviz
      - run:
          name: Build Docs Site
          command: mkdocs build --clean
      - run:
          name: Copy config file to gh-pages branch
          command: cp -r .circleci site/
      - add_ssh_keys:
          fingerprints:
            - "7b:4c:eb:72:48:4d:3f:cd:05:cc:16:46:33:f9:fb:8a"
      - run:
          name: Upload
          command: mkdocs gh-deploy
