version: 2
jobs:
  build:
    branches:
      only: master
    environment:
      CIRCLE_BRANCH: master
      TZ: '/usr/share/zoneinfo/Etc/UTC'
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    docker:
      - image: circleci/python:3.6-jessie-browsers
    steps:
      - checkout
      - run: sudo pip install -q mkdocs mkdocs-material pygments
      - run:
          name: Build Docs Site
          command: mkdocs build --clean
      - add_ssh_keys:
          fingerprints:
            - "4d:6b:08:ae:dc:74:97:f1:7c:3e:12:70:08:3d:4e:56"
      - run:
          name: Upload
          command: mkdocs gh-deploy
